# Generated by Django 4.2 on 2024-05-14 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcLastCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('btnID', models.CharField(max_length=200)),
                ('command', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='DuctMaxValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_value', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DuctPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('btnID', models.CharField(max_length=200)),
                ('position', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='FanButtonModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('btnID', models.CharField(max_length=200)),
                ('model', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Mode',
            fields=[
                ('mode_id', models.AutoField(primary_key=True, serialize=False)),
                ('mode_name', models.CharField(blank=True, max_length=200, null=True)),
                ('mode_description', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SensorData1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('pressure', models.FloatField()),
                ('altitude', models.FloatField()),
                ('lux', models.FloatField()),
                ('dustDensity', models.FloatField()),
                ('windSpeed', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=200, null=True)),
                ('aqi', models.FloatField(blank=True, null=True)),
                ('tvoc', models.FloatField(blank=True, null=True)),
                ('eco2', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SensorData2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('pressure', models.FloatField()),
                ('altitude', models.FloatField()),
                ('lux', models.FloatField()),
                ('dustDensity', models.FloatField()),
                ('windSpeed', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=200, null=True)),
                ('aqi', models.FloatField(blank=True, null=True)),
                ('tvoc', models.FloatField(blank=True, null=True)),
                ('eco2', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SensorData3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('pressure', models.FloatField()),
                ('altitude', models.FloatField()),
                ('lux', models.FloatField()),
                ('dustDensity', models.FloatField()),
                ('windSpeed', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=200, null=True)),
                ('aqi', models.FloatField(blank=True, null=True)),
                ('tvoc', models.FloatField(blank=True, null=True)),
                ('eco2', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SensorData4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('pressure', models.FloatField()),
                ('altitude', models.FloatField()),
                ('lux', models.FloatField()),
                ('dustDensity', models.FloatField()),
                ('windSpeed', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=200, null=True)),
                ('aqi', models.FloatField(blank=True, null=True)),
                ('tvoc', models.FloatField(blank=True, null=True)),
                ('eco2', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SensorData5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('pressure', models.FloatField()),
                ('altitude', models.FloatField()),
                ('lux', models.FloatField()),
                ('dustDensity', models.FloatField()),
                ('windSpeed', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=200, null=True)),
                ('aqi', models.FloatField(blank=True, null=True)),
                ('tvoc', models.FloatField(blank=True, null=True)),
                ('eco2', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SensorData6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('pressure', models.FloatField()),
                ('altitude', models.FloatField()),
                ('lux', models.FloatField()),
                ('dustDensity', models.FloatField()),
                ('windSpeed', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=200, null=True)),
                ('aqi', models.FloatField(blank=True, null=True)),
                ('tvoc', models.FloatField(blank=True, null=True)),
                ('eco2', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='ButtonModel',
            new_name='DuctButtonModel',
        ),
        migrations.CreateModel(
            name='ModeElements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode_identifier', models.CharField(max_length=200)),
                ('mode_command', models.CharField(blank=True, max_length=20, null=True)),
                ('mode_type', models.CharField(blank=True, max_length=5, null=True)),
                ('mode_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controller.mode')),
            ],
        ),
    ]
