# Generated by Django 4.2 on 2024-02-04 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0002_aclastcommand_ductbuttonmodel_fanbuttonmodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DuctPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('btnID', models.CharField(max_length=200)),
                ('position', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Mode',
            fields=[
                ('mode_id', models.AutoField(primary_key=True, serialize=False)),
                ('mode_name', models.CharField(max_length=200)),
                ('mode_description', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModeElements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode_identifier', models.CharField(max_length=200)),
                ('mode_type', models.CharField(blank=True, max_length=5, null=True)),
                ('mode_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controller.mode')),
            ],
        ),
    ]
