# Generated by Django 4.2 on 2024-05-29 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0002_aclastcommand_ductmaxvalue_ductposition_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LightModes',
            fields=[
                ('mode_id', models.AutoField(primary_key=True, serialize=False)),
                ('mode_name', models.CharField(blank=True, max_length=200, null=True)),
                ('on_lights', models.CharField(blank=True, max_length=400, null=True)),
                ('color', models.CharField(blank=True, max_length=200, null=True)),
                ('brightness', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
