# Generated by Django 4.2 on 2024-07-25 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0003_lightmodes'),
    ]

    operations = [
        migrations.CreateModel(
            name='PowerIPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_ip', models.CharField(blank=True, max_length=200, null=True)),
                ('pi_ip', models.CharField(blank=True, max_length=200, null=True)),
                ('duct_1_ip', models.CharField(blank=True, max_length=200, null=True)),
                ('duct_2_ip', models.CharField(blank=True, max_length=200, null=True)),
                ('duct_3_ip', models.CharField(blank=True, max_length=200, null=True)),
                ('duct_4_ip', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
