# Generated by Django 4.2 on 2024-02-04 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0003_ductposition_mode_modeelements'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeelements',
            name='mode_command',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='mode',
            name='mode_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
