# Generated by Django 4.2 on 2024-02-05 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0005_ductpositions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DuctPositions',
        ),
    ]
