# Generated by Django 4.2 on 2024-05-09 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0006_delete_ductpositions'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('pressure', models.FloatField()),
                ('altitude', models.FloatField()),
                ('lux', models.FloatField()),
                ('dustDensity', models.FloatField()),
                ('windSpeed', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=200, null=True)),
                ('aqi', models.FloatField(blank=True, null=True)),
                ('tvoc', models.FloatField(blank=True, null=True)),
                ('eco2', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
