# Generated by Django 4.2 on 2024-04-24 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0007_sensordata'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata',
            name='aqi',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='eco2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='status',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='tvoc',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='windSpeed',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
