# Generated by Django 4.2 on 2024-05-09 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0007_sensordata'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('pressure', models.FloatField()),
                ('altitude', models.FloatField()),
                ('lux', models.FloatField()),
                ('dustDensity', models.FloatField()),
                ('windSpeed', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=200, null=True)),
                ('aqi', models.FloatField(blank=True, null=True)),
                ('tvoc', models.FloatField(blank=True, null=True)),
                ('eco2', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SensorData3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('pressure', models.FloatField()),
                ('altitude', models.FloatField()),
                ('lux', models.FloatField()),
                ('dustDensity', models.FloatField()),
                ('windSpeed', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=200, null=True)),
                ('aqi', models.FloatField(blank=True, null=True)),
                ('tvoc', models.FloatField(blank=True, null=True)),
                ('eco2', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SensorData4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('pressure', models.FloatField()),
                ('altitude', models.FloatField()),
                ('lux', models.FloatField()),
                ('dustDensity', models.FloatField()),
                ('windSpeed', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=200, null=True)),
                ('aqi', models.FloatField(blank=True, null=True)),
                ('tvoc', models.FloatField(blank=True, null=True)),
                ('eco2', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SensorData5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('pressure', models.FloatField()),
                ('altitude', models.FloatField()),
                ('lux', models.FloatField()),
                ('dustDensity', models.FloatField()),
                ('windSpeed', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=200, null=True)),
                ('aqi', models.FloatField(blank=True, null=True)),
                ('tvoc', models.FloatField(blank=True, null=True)),
                ('eco2', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SensorData6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('pressure', models.FloatField()),
                ('altitude', models.FloatField()),
                ('lux', models.FloatField()),
                ('dustDensity', models.FloatField()),
                ('windSpeed', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=200, null=True)),
                ('aqi', models.FloatField(blank=True, null=True)),
                ('tvoc', models.FloatField(blank=True, null=True)),
                ('eco2', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='SensorData',
            new_name='SensorData1',
        ),
    ]
