# Generated by Django 4.2 on 2024-04-27 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0008_sensordata_aqi_sensordata_eco2_sensordata_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensordata',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
