from django.urls import path
from . import views

urlpatterns = [
    path('', views.indexPage, name='indexPage'),
    path('index/<str:pk>/', views.index, name='index'),
    path('light/<str:pk>/', views.light, name='light'),
    path('login/', views.loginPage, name='loginPage'),
    path('logout/', views.logoutPage, name='logoutPage'),
    path('supplyCommand/', views.supplyCommand, name='supplyCommand'),
    path('exhaustCommand/', views.exhaustCommand, name='exhaustCommand'),
    path('offCommand/', views.offCommand, name='offCommand'),
    path('fanStatusCommand/', views.fanStatusCommand, name='fanStatusCommand'),
    path('fanBtnUpdate/', views.fanBtnUpdate, name='fanBtnUpdate'),
    path('semiCloseCommand/', views.semiCloseCommand, name='semiCloseCommand'),
    path('semiOpenCommand/', views.semiOpenCommand, name='semiOpenCommand'),
    path('openCommand/', views.openCommand, name='openCommand'),
    path('closeCommand/', views.closeCommand, name='closeCommand'),
    path('ductStatusCommand/', views.ductStatusCommand, name='ductStatusCommand'),
    path('multipleSelect/', views.multipleSelect, name="multipleSelect"),
    path('executeLightCommand/', views.executeLightCommand, name='executeLightCommand'),
    path('lightOverlayUpdate/', views.lightOverlayUpdate, name='lightOverlayUpdate'),
    path('saveLights/', views.saveLights, name='saveLights'),
    path('fans/', views.fans, name='fans'),
    path('ducts/', views.ducts, name='ducts'),
    # path('ductsPosition/', views.ductsPosition, name='ductsPosition'),
    # path('ductPositionUpdate/<str:btnID>/<int:value>', views.ductPositionUpdate, name='ductPositionUpdate'),
    # path('duct/', views.ductPage, name='ductPage'),
    # path('ac/', views.acPage, name='acPage'),
    # path('fans/', views.fans, name='fans'),
    # path('ducts/', views.ducts, name='ducts')
    path('createMode/', views.createMode, name='createMode'),
    path('addMode/', views.addMode, name='addMode'),
    path('getModes', views.getModes, name='getModes'),
    path('executeMode', views.executeMode, name='executeMode'),
    path('deleteMode', views.deleteMode, name='deleteMode'),
    path('ductsPosition', views.ductsPosition, name='ductsPosition'),
    path('ductPositionUpdate/', views.ductPositionUpdate, name='ductPositionUpdate'),
    path('sensorDataEntry/', views.sensorDataEntry, name='sensorDataEntry'),
    path('getDuctMaxValue/', views.getDuctMaxValue, name='getDuctMaxValue'),
    path('export/', views.export_sensor_data, name='export_sensor_data'),
    path('export/sensor1/', views.export_sensor_data1_csv, name='export_sensor_data1_csv'),
    path('export/sensor2/', views.export_sensor_data2_csv, name='export_sensor_data2_csv'),
    path('export/sensor3/', views.export_sensor_data3_csv, name='export_sensor_data3_csv'),
    path('export/sensor4/', views.export_sensor_data4_csv, name='export_sensor_data4_csv'),
    path('export/sensor5/', views.export_sensor_data5_csv, name='export_sensor_data5_csv'),
    path('export/sensor6/', views.export_sensor_data6_csv, name='export_sensor_data6_csv'),

    path('powerSensor/', views.power_sensor, name='power_sensor'),
    path('powerPi/', views.power_pi, name='power_pi'),
    path('powerDuct/', views.power_duct, name='power_duct'),

    path('setOffset/', views.setOffset, name='setOffset'),
]
